apiVersion: v1
kind: Pod
metadata:
 name: k8s-fleetman-queue
 labels:
   app: k8s-fleetman-queue
   release: "1"
spec:
  containers:
  - name: k8s-fleetman-queue
    image: richardchesterwood/k8s-fleetman-queue
