apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

---
apiVersion: v1
kind: Pod
metadata:
 name: k8s-fleetman-queue
 labels:
   queue: k8s-fleetman-queue
   release: "1"
spec:
  containers:
  - name: k8s-fleetman-queue
    image: richardchesterwood/k8s-fleetman-queue:release1
