kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: fleetman-webapp
spec:
  selector:
    # This define which PODs are going to be represented by this Service
    #
    app: webapp
    # release: "0-5"
    # Accept traffic sent to port 80
  ports:
    - name: http
      port: 80
      nodePort: 30080
  #      targetPort: 80
  # Create an HA proxy in the cloud provider
  # with an External IP address - *Only supported
  # by some cloud providers*
  type: NodePort

---

kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: fleetman-position-tracker
spec:
  selector:
    # This define which PODs are going to be represented by this Service
    #
    app: position-tracker

    # Accept traffic sent to port 80
  ports:
    - name: http
      port: 8080

  type: ClusterIP

---

kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: fleetman-api-gateway
spec:
  selector:
    # This define which PODs are going to be represented by this Service
    #
    app: api-gateway

    # Accept traffic sent to port 80
  ports:
    - name: http
      port: 8080

  type: ClusterIP
