kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: fleetman-webapp
spec:
  selector:
    # This define which PODs are going to be represented by this Service
    app: webapp
  ports:
    - name: http
      port: 80
      nodePort: 30080
  type: NodePort

---
  kind: Service
  apiVersion: v1
  metadata:
    name: fleetman-queue
  spec:
    selector:
      app: queue
    ports:
      - name: http
        port: 8161
        nodePort: 30010
      - name: endpoint
        port: 61616
    type: NodePort

---

kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: fleetman-position-tracker
spec:
  selector:
    # This define which PODs are going to be represented by this Service
    #
    app: position-tracker

    # Accept traffic sent to port 80
  ports:
    - name: http
      port: 8080

  type: ClusterIP

---

kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: fleetman-api-gateway
spec:
  selector:
    # This define which PODs are going to be represented by this Service
    #
    app: api-gateway

    # Accept traffic sent to port 80
  ports:
    - name: http
      port: 8080

  type: ClusterIP
